### ISSUE TITLE
Pre-trained models on Comics, ChestX, Paintings dataset

### ISSUE THREAD

**Issue by abhishekaich27** [krishnakanthnakka/Transferable_Perturbations#1]
Hi @krishnakanthnakka, 

We are building our next work on your wonderful NeurIPS paper and were wondering if you could share your pre-trained models (i.e. classifiers you use to train your generators against) on Comics, ChestX, Paintings for comparisons like Table 2. It would keep the comparisons fair and easy to compare with.

Needless to say, we will cite your work and acknowledge the help :)!

**Comment by krishnakanthnakka** [comment]
For Table 2, we use the PyTorch ImageNet classifiers as discriminators and use Comics/Painting/ChestX datasets to train the generator.  For Table 3, we use the open-source implementation of chestXNet available [here](https://github.com/zoogzog/chexnet). Hope it clarifies.

I also bring to your attention a recent work from [ICLR 2022](https://github.com/Alibaba-AAIG/Beyond-ImageNet-Attack)  in a cross-domain setting that also contains the pre-trained models of CUB, Cars, Aircraft, etc. on different backbones.
